// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WallpaperApi.Data;

#nullable disable

namespace WallpaperApi.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WallpaperApi.Data.Model.Resolutions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Resolution1080P")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resolution2K")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resolution4K")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resolution720P")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReviewProcessId")
                        .HasColumnType("int");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WallpaperId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReviewProcessId");

                    b.HasIndex("WallpaperId");

                    b.ToTable("Resolutions");
                });

            modelBuilder.Entity("WallpaperApi.Data.Model.ReviewProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Extention")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WallpaperTag")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("ReviewProcess");
                });

            modelBuilder.Entity("WallpaperApi_Model.Model.Creator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte[]>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UserImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Creator");
                });

            modelBuilder.Entity("WallpaperApi_Model.Model.Wallpaper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Extention")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WallpaperTag")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Wallpaper");
                });

            modelBuilder.Entity("WallpaperApi.Data.Model.Resolutions", b =>
                {
                    b.HasOne("WallpaperApi.Data.Model.ReviewProcess", "ReviewProcess")
                        .WithMany("Resolutions")
                        .HasForeignKey("ReviewProcessId");

                    b.HasOne("WallpaperApi_Model.Model.Wallpaper", "Wallpaper")
                        .WithMany("Resolutions")
                        .HasForeignKey("WallpaperId");

                    b.Navigation("ReviewProcess");

                    b.Navigation("Wallpaper");
                });

            modelBuilder.Entity("WallpaperApi.Data.Model.ReviewProcess", b =>
                {
                    b.HasOne("WallpaperApi_Model.Model.Creator", "Creators")
                        .WithMany("ReviewProcesses")
                        .HasForeignKey("CreatorId");

                    b.Navigation("Creators");
                });

            modelBuilder.Entity("WallpaperApi_Model.Model.Wallpaper", b =>
                {
                    b.HasOne("WallpaperApi_Model.Model.Creator", null)
                        .WithMany("Wallpapers")
                        .HasForeignKey("CreatorId");
                });

            modelBuilder.Entity("WallpaperApi.Data.Model.ReviewProcess", b =>
                {
                    b.Navigation("Resolutions");
                });

            modelBuilder.Entity("WallpaperApi_Model.Model.Creator", b =>
                {
                    b.Navigation("ReviewProcesses");

                    b.Navigation("Wallpapers");
                });

            modelBuilder.Entity("WallpaperApi_Model.Model.Wallpaper", b =>
                {
                    b.Navigation("Resolutions");
                });
#pragma warning restore 612, 618
        }
    }
}
